import AboutContent from "@/components/AboutContent";

import Menu from "@/components/Menu/Menu";
import Head from "next/head";

function Sobre(): React.ReactElement {
  return (
    <>
      <Head>
        <br></br>
        <title>Armando - Sobre Empresa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Menu />
        <AboutContent />
   
      </main>
    </>
  );
}
export default Sobre;
